name: 'Setup gitsign'
description: 'Install and authorize gitsign'
branding:
  icon: box
  color: green
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -ex

      curl -fsL https://github.com/sigstore/gitsign/releases/download/v0.0.2-alpha/gitsign_0.0.2-alpha_linux_amd64 -o /usr/local/bin/gitsign
      chmod +x /usr/local/bin/gitsign

      git config --global commit.gpgsign true  # Sign all commits
      git config --global gpg.x509.program gitsign  # Use gitsign for signing
      git config --global gpg.format x509  # gitsign expects x509 args
