on: [push]
jobs:
  hello_world_job:
    permissions:                         
      id-token: write  # Enable OIDC
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: wlynch/gitsign-action@main
      - shell: bash
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          git commit --allow-empty --message="Signed commit"
          git --no-pager log --show-signature -1

          git cat-file commit HEAD | sed -n '/BEGIN/, /END/p' | sed 's/^ //g' | sed 's/gpgsig //g' | sed 's/SIGNED MESSAGE/PKCS7/g' | openssl pkcs7 -print -print_certs -text

