name: 'Make a PR'
on: [pull_request]

jobs:
  new_pr:
    permissions:                         
      id-token: write  # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Make a new pull request
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: wlynch/gitsign-action@main
    - name: Change files
      shell: bash
      run: |
        date > date.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.2
      with:
        commit-message: 'tacocat is the best palindrome'
        title: 'New PR!'
        body: >
          foo
