name: 'Make a PR'
on: [push]

runs:
  using: "composite"
  steps:
  - uses: chainguard-dev/actions/setup-gitsign@main
  - name: Create Pull Request
    uses: peter-evans/create-pull-request@v4.0.2
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      commit-message: 'tacocat is the best palindrome'
      title: 'New PR!'
      body: >
        foo
      delete-branch: true
