on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify commit
    steps:
      - uses: actions/checkout@v3
      - uses: wlynch/gitsign-action@main
      - shell: bash
        run: |
          git verify-commit HEAD

